<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class InventarisTableSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('inventaris')->insert([
            [
                'id' => 1,
                'room_id' => 1,
                'nama_barang' => 'Komputer',
                'spesifikasi' => '4PC (Core i7-10700, 32GB RAM, 256GB SSD, 1TB HDD), 1 PC (Core i7-7700, 16GB RAM, 256GB SSD)',
                'deskripsi' => '-',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'room_id' => 1,
                'nama_barang' => 'Monitor',
                'spesifikasi' => '24" Full HD',
                'deskripsi' => 'LG',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'room_id' => 1,
                'nama_barang' => 'Keyboard',
                'spesifikasi' => 'Keyboard Kabel',
                'deskripsi' => 'Logitech K200',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'room_id' => 1,
                'nama_barang' => 'Mouse',
                'spesifikasi' => 'Mouse Kabel',
                'deskripsi' => 'Logitech M100',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'room_id' => 1,
                'nama_barang' => 'Meja Komputer (Laci)',
                'spesifikasi' => 'Meja + 3 Laci',
                'deskripsi' => '-',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'room_id' => 1,
                'nama_barang' => 'Meja Komputer',
                'spesifikasi' => '-',
                'deskripsi' => '-',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'room_id' => 1,
                'nama_barang' => 'Meja Rapat',
                'spesifikasi' => '-',
                'deskripsi' => '-',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'room_id' => 1,
                'nama_barang' => 'Kursi Lipat',
                'spesifikasi' => '-',
                'deskripsi' => '-',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'room_id' => 1,
                'nama_barang' => 'Kursi Tengah',
                'spesifikasi' => '-',
                'deskripsi' => 'Uno Office Chair',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'room_id' => 1,
                'nama_barang' => 'Stopkontak',
                'spesifikasi' => 'Stopkontak 5 Lubang',
                'deskripsi' => '-',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'room_id' => 1,
                'nama_barang' => 'Dispenser',
                'spesifikasi' => '-',
                'deskripsi' => 'Modena',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'room_id' => 1,
                'nama_barang' => 'Rak Koran/Majalah',
                'spesifikasi' => '-',
                'deskripsi' => '-',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'room_id' => 1,
                'nama_barang' => 'AC',
                'spesifikasi' => '-',
                'deskripsi' => 'Daikin',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'room_id' => 1,
                'nama_barang' => 'Banner Unikost',
                'spesifikasi' => 'Banner vertikal roll up',
                'deskripsi' => '-',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 15,
                'room_id' => 1,
                'nama_barang' => 'Banner Rumahraga',
                'spesifikasi' => 'Banner vertikal roll up',
                'deskripsi' => '-',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 16,
                'room_id' => 1,
                'nama_barang' => 'Banner Jacult',
                'spesifikasi' => 'Banner vertikal roll up',
                'deskripsi' => '-',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 17,
                'room_id' => 1,
                'nama_barang' => 'Banner TI-D3',
                'spesifikasi' => 'Banner vertikal roll up',
                'deskripsi' => '-',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 18,
                'room_id' => 1,
                'nama_barang' => 'Banner D4 - Broadcasting',
                'spesifikasi' => 'Banner vertikal roll up',
                'deskripsi' => '-',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 19,
                'room_id' => 1,
                'nama_barang' => 'Banner film "Brush with Danger"',
                'spesifikasi' => 'Banner vertikal roll up',
                'deskripsi' => '-',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 20,
                'room_id' => 1,
                'nama_barang' => 'Banner Lulusan Angkatan 2020',
                'spesifikasi' => 'Banner Horizontal',
                'deskripsi' => '-',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 21,
                'room_id' => 1,
                'nama_barang' => 'Banner Lulusan Angkatan 2021',
                'spesifikasi' => 'Banner vertikal',
                'deskripsi' => '-',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 22,
                'room_id' => 1,
                'nama_barang' => 'Proyektor',
                'spesifikasi' => 'Viewsonic',
                'deskripsi' => '-',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 23,
                'room_id' => 1,
                'nama_barang' => 'Kabel HDMI',
                'spesifikasi' => '-',
                'deskripsi' => 'Kabel HDMI Proyektor',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 24,
                'room_id' => 1,
                'nama_barang' => 'Lemari Kaca Geser',
                'spesifikasi' => '-',
                'deskripsi' => '-',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 25,
                'room_id' => 1,
                'nama_barang' => 'Lemari Kaca',
                'spesifikasi' => '-',
                'deskripsi' => '-',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 26,
                'room_id' => 1,
                'nama_barang' => 'Papan Tulis',
                'spesifikasi' => '-',
                'deskripsi' => '-',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 27,
                'room_id' => 1,
                'nama_barang' => 'Tempat sampah plastik',
                'spesifikasi' => '-',
                'deskripsi' => '-',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 28,
                'room_id' => 1,
                'nama_barang' => 'Stand X-Banner',
                'spesifikasi' => '-',
                'deskripsi' => '-',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 29,
                'room_id' => 1,
                'nama_barang' => 'Poster Penelitian',
                'spesifikasi' => '-',
                'deskripsi' => '-',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 30,
                'room_id' => 1,
                'nama_barang' => 'Lampu Dinding',
                'spesifikasi' => 'Lampu TL',
                'deskripsi' => '-',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 31,
                'room_id' => 1,
                'nama_barang' => 'Ember Plastik',
                'spesifikasi' => '-',
                'deskripsi' => '-',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 32,
                'room_id' => 1,
                'nama_barang' => 'Kalender Tahun 2023',
                'spesifikasi' => '-',
                'deskripsi' => 'Kalender Meja',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
